---
- hosts: all
  tasks:
    - name: 'Instala pacotes de dependencia do sistema operacional'
      apt:
        name: ['php5', 'apache2', 'libapache2-mod-php5', 'php5-gd']
        state: latest
      become: yes
